#include <iostream>
#include "head.hpp"

int main()
{
    vector_Default_constructor();
    vector_FillConstructor();
    vector_FillConstructorSizedValue();
    vector_RangeConstructor();
    vector_CopyConstructor();
    vectorAssignOperator();
    vectorIteratorBegin();
    vectorConstIteratorBegin();
    vectorIteratorEnd();
    vectorConstIteratorEnd();
    vectorIteratorRbegin();
    vectorConstIteratorRbegin();
    vectorIteratorRend();
    vectorConstIteratorRend();
    vecotSizeMaximum();
    vectorResize();
    vectorEmtyTrue();
    vectorEmtyFalse();
    vectorOperator();
    vectorConstOperator();
    vectorAt();
    vectorConstAt();
    vectorFront();
    vectorConstFront();
    vectorBack();
    vectorConstBack();
    vectorAssignRange();
    vectorPushBackEmpty();
    vectorPushBack();
    vectorPopBack();
    vectorInsertSingleElement();
    vectorInsertFill();
    vectorEraseSingleElement();
    vectorEraseRange();
    vectorSwap();
    vectorClear();
    vectorRealationEqualTrue();
    vectorRealationEqualFalse();
    vectorRealationNotEqualTrue();
    vectorRealationNotEqualFalse();
    vectorSmallTrue();
    vectorSmallFalse();
    vectorMoreTrue();
    vectorMoreFalse();
}